module.exports = {
  theme: {
    extend: {
      fontFamily: {
        archivo: ["Archivo", "sans-serif"],
      },
      colors: {
        cactus: {
          '050': '#EFFEF9',
          '100': '#E9FEF7',
          '200': '#C7FBE2',
          '300': '#39E4AB',
          '400': '#13D393',
          '500': '#00BF7F',
          '600': '#00A67C',
          '700': '#1A926A',
          '800': '#097F58',
          '900': '#005B3D',
        },
        seaside: {
          '050': '#E1F5FE',
          '100': '#B3E5FC',
          '200': '#81D4FA',
          '300': '#4FC3F7',
          '400': '#29B6F6',
          '500': '#03A9F4',
          '600': '#039BE5',
          '700': '#0288D1',
          '800': '#0277BD',
          '900': '#01579B',
          'A100': '#80D8FF',
          'A200': '#40C4FF',
          'A400': '#00B0FF',
          'A700': '#0091EA',
        },
      },
    },
  },
  variants: {
    backgroundColor:  ['responsive', 'hover', 'focus', 'active', 'group-hover'],
    borderWidth:      ['responsive', 'hover', 'focus', 'active', 'group-hover'],
    boxShadow:        ['responsive', 'hover', 'focus', 'active', 'group-hover'],
    display:          ['responsive', 'hover', 'focus', 'active', 'group-hover'],
    rotate:           ['responsive', 'hover', 'focus', 'active', 'group-hover'],
    scale:            ['responsive', 'hover', 'focus', 'active', 'group-hover'],
    size:             ['responsive', 'hover', 'focus', 'active', 'group-hover'],
    textColor:        ['responsive', 'hover', 'focus', 'active', 'group-hover'],
  },
  plugins: [],
};
